### PR TITLE
Add Just Friends, Peaks Stock, Ornament&Crime Cheatsheets

### PR DESCRIPTION
**Pull request by delta-6400**
Add Just Friends cheat sheet with 6 standard modes and 6 run modes.

### CODE REVIEW

**Comment by boourns** [comment]
Woo! thank you!

A bit of additional formatting is required to have it show up in the ios app and web app properly, @delta-6400 is it ok if I do that on top of your code?

Is there a name or pseudonym you would like to be referred to when crediting your contribution?

**Comment by delta-6400** [comment]
Sure, go for it @boourns! I just tried to copy the Rings formatting as best I could! 

I’ll take a look at the changes you post so that I can try to have ‘em in place next time I do one!

**Comment by delta-6400** [comment]
Ah the format for the Rings folder has even changed since last night it seems. I see there is now an xml “module.xml” file and a header for each mode now. 

I might take a shot at Peaks today!

**Comment by boourns** [comment]
There are two folders - the one in data/ is the one to write by hand.  The folder under /web/modules gets generated for the stnthmodes.com website.  Also you will need to add an entry in data/modules.xml.

**Comment by boourns** [comment]
this looks really awesome.  will get it merged after the holidays!  Thank you!

**Comment by delta-6400** [comment]
word!  Looking forward to seeing them in the app eventually!

I just tried adapting the ornament and crime web manual to this format - hopefully everything worked out alright!

**Comment by boourns** [comment]
I had some time to look at this today, overall it looks great.  I pushed 1 commit to this branch that just fixes a few tiny XML issues.  On master I added some tests and travis CI so that new pull requests will get feedback if everything is seemingly working or not - it might not be perfect however so if you see a red test run that seems suspect don't hesitate to ask.

Really great work!

There's a few things left to do before it can be merged:
- Just Friends should be separate HTML files with a module.xml file.  I added a modules.xml entry but commented it out so that the branch is currently working.
- The O_C documentation is currently not open source.  We will either need permission from Max (cc @mxmxmx), who I will now email, or someone will need to rewrite the documentation into a cheatsheet free from copyright issues.  Otherwise for now we'll have to remove that module from the pull request, but lets see what Max says first.

**Comment by boourns** [comment]
Let me know if you want to do the Just Friends HTML work.  If you don't have time that's fine, I can add it myself next week.

**Comment by delta-6400** [comment]
I’ll conform JF to the standard format today!

Peaks looked good though?

Also, didn’t even think abt that w/ OC, thanks for checking on that!

**Comment by boourns** [comment]
Peaks looks awesome!!

**Comment by delta-6400** [comment]
Great, looks like the commit passed!

JF is now properly formatted.  

I don't need to do anything else, it will run all the necessary tests on its own yeah?

**Comment by boourns** [comment]
On branches rebased off of master, yes it will run all the tests.  I'm not sure if this branch will because it doesn't have the .travis.yml file present so it may be a fake pass.
But that's ok - I'll check tomorrow.  It might make sense to separate O_C into its own PR while we figure out licensing.  If everything else is good I'll get the others merged and a new version of the app to the App Store.

**Comment by boourns** [comment]
@delta-6400 Is it ok if I separate out O_C from the other manuals into it's own pull request?  I'm still waiting on one email from the manual authors and I think it'll need some further style changes before it fits the other content.

Then we can get these merged and a new release out next week

**Comment by delta-6400** [comment]
Yes go for it!

sorry very busy this week!

Thanks

**Comment by boourns** [comment]
Alright, rebased this against master & reverted O_C for now.  Looks great, merging!  Thank you!

One thing I would like to add in the future is a "General information" blurb on each module, linking to it's product page and manual etc.. It would also be a great spot to put credits for contributed cheat sheets.

**Pull request merged**
