### PR TITLE
add mannequins W/ info

### LINKED ISSUE #37: w/
requested over email.

It's a good fit for Modes, however.. I don't own the app and don't understand the module myself.  If anyone wants to take a stab at writing a rough draft I'm more than happy to convert it to the right format

### PR DESCRIPTION
**Pull request by gmarinov**
fix #37 - first pass W/

covers:
 - nav
 - live
 - cue
 - global
 - system / boot

I wasn't able to get the whole project to run on my system, here are a couple of sample screens anyway.

Screen Shot 2019-06-23 at 03 16 58

Screen Shot 2019-06-23 at 03 14 24

### CODE REVIEW

**Comment by boourns** [comment]
Woo!!!  Thank you!

I'll get this merged this week, this looks really great!

If you list what parts failed to run on your system and give me the console output I might be able to get it working.

**Comment by gmarinov** [comment]
@boourns I think it really didn't want to install `nokogiri`

```
Installing nokogiri 1.9.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

...

libxml2 is missing.  Please locate mkmf.log to investigate how it is failing.
-----
*** extconf.rb failed ***

...

An error occurred while installing nokogiri (1.9.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.9.1' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  nokogiri
```

I didn't try very hard. I'm not familiar with Ruby, and my macOS hasn't a great many of its dependencies.

`nokogiri-1.9.1/mkmf.log` contains:

```
Undefined symbols for architecture i386:
  "_xmlParseDoc", referenced from:
      _t in conftest-27c7e5.o
ld: symbol(s) not found for architecture i386

...

conftest.c:15:13: error: conflicting types for 'xmlParseDoc'
extern void xmlParseDoc();
...

xmlParseDoc             (const xmlChar *cur);
                ^
conftest.c:16:27: error: too few arguments to function call, single argument 'cur' was not specified
int t(void) { xmlParseDoc(); return 0; }

```

anyway, hope it looks fine in the app.

**Comment by boourns** [comment]
Gotcha, don't worry about it I will take it from here.

Would you like some Modes stickers?  Email me your address, tom@burns.ca

Thanks again!

**Comment by boourns** [comment]
Working on a new build for Modes, thanks again.. this looks really nice in the app

**Pull request merged**
