### PR TITLE
Added Instruo Arbhar pages

### PR DESCRIPTION
**Pull request by joshdavenport**
Think this about covers most of the more obscure features and button combinations of this module. There's loads more that _could_ be added. Hopefully this aligns with the style/approach of the project.

### CODE REVIEW

**Comment by boourns** [comment]
Amazing!! On first glance it looks perfect, I'll test it and get it merged ASAP.  If you want to add a sentence like "This cheatsheet provided by (your name)" with a link to your website or something, go ahead.  Thanks!

**Comment by joshdavenport** [comment]
Nice of you to suggest that, I'll do so. Thanks!

**Comment by boourns** [comment]
Sorry for the delay, getting back into this after the holidays.

Everything looks perfect in the app except the MOD CV parameters, I think there's a vertical alignment issue between the columns so it's hard to see exactly what lines up

image

This morning I'm going to update the disting manual to latest firmware revision, and then if you haven't had time to fix this I'll fix it and get a release out

**Comment by joshdavenport** [comment]
Between A & B and X & Y were some tables creating a diagram demonstrating jumper positions. Clearly they're not rendering in the app properly. I've replaced with with SVG graphics which should be better and added some HRs to help with parsing the information too.

**Comment by boourns** [comment]
Amazing, I'll check this out when I'm done updating disting!

**Comment by boourns** [comment]
Looks good now, will get the app submitted this morning so it should be live tomorrow.  Thanks again!

**Comment by boourns** [comment]
image

**Comment by boourns** [comment]
New release is already live! Fastest Apple review I've ever experienced!

**Comment by joshdavenport** [comment]
Amazing! Can't see the update yet, but I'm sure it'll appear in the next day or two.

Hoping to contribute to some other modules too when I get the time (got some ideas for Mimeophon, Maths, PNW).

**Pull request merged**
