### PR TITLE
Add Pico Voice

### PR DESCRIPTION
**Pull request by benirose**
This will add pages for Erica Synth's Pico Voice. Let me know if there are any changes you need me to make to formatting.

### CODE REVIEW

**Comment by boourns** [comment]
Amazing, thank you! I'll check this in the next couple days

**Comment by benirose** [comment]
Definitely! I can't say it wasn't a selfish motivation, as I just got mine ;)

How often do you publish updates here to the app? Also is there a request list somewhere of modules to do? This was pretty easy for me, I could maybe knock a few more out!

**Comment by boourns** [comment]
Selfish motivation is what led me to add most of these modules to the app as well, so don't apologize.  If you have others you want to do for selfish reasons, I would start with that.  I have some open issues listed, but I'm also hiring a writer to start working on it more consistently.  I usually cut releases when I have 3 or more modules added or updated, unless there's a more pressing issue.  If you'd be interested in doing some paid module writing, please email me! tom@burns.ca

**Comment by benirose** [comment]
I'm getting a Pam's this week, so I'll take a swing at that next. I'm not ready to commit to a paying gig yet, but maybe I'll see after that PR!

**Comment by boourns** [comment]
Looks super great in the app!  Merging this, will update website and get a release out in the next couple weeks.

image

**Comment by benirose** [comment]
Awesome! I've been too busy playing with Pams to work on the docs but I'll try to get to it shortly!

**Comment by boourns** [comment]
No rush, thank you Ben!

ALM never responded over email, I think I may be on a forum where they are active so I will try there.

Cheers
Tom

**Comment by benirose** [comment]
Yo mate, I don't mean to be a pest, but any chance you can push the update to the app store soon?

**Comment by boourns** [comment]
Yeah definitely, sorry.  I have a new project in the works taking up all my time but ill get this out.  Need to update Disting first but I'll put in the work.

**Comment by boourns** [comment]
Still no release - not upgrading my laptop to an OSX new enough to release iOS apps anymore, so gotta do the build from my wife's new laptop, annoyingly..

**Comment by benirose** [comment]
Oh man, I know that feel. Thanks for the update.

I noticed the website hasn't been updated since the last few MRs either, is that easier to deploy? Also, let me know if I can help with the build process either now or in the future. I know it's more complicated because there's money involved as it's a paid app so that part of the pipeline isn't public, but I'm not interested in any of that, just want to help keep this beautiful resource to the community going!

**Comment by boourns** [comment]
Website is now updated, sorry for that.  It's much easier to deploy than the iOS app update, this time around.  I'm now having issues logging into my itunes connect account and have an open ticket with apple support, hopefully they fix it in the next couple days.

**Pull request merged**
