### PR TITLE
added plaits stock

### PR DESCRIPTION
**Pull request by gitdistill**
images didn't show up and plaits.css. assuming i missed a step, but its a start.

### CODE REVIEW

**Comment by gitdistill** [comment]
oops and copypasta on the buttons in the info section

**Comment by boourns** [comment]
I made a few small changes to make it look better in-app.  

I think testing the pages via the jekyll website is probably a worse idea than just opening the raw `file://` url in a narrow browser window.

Either way, this is great work.  Thanks!  I'll likely do a release near the end of the week.  Cheers!

**Comment by gitdistill** [comment]
cool, yea its a start. I have some ideas to improve but wanted to see the actual in app version. but I assume that requires a full setup of dev env. Not sure what that entails.

Also wanna do a pass at another module the TNRS Tuesday. I'll open an issue.

**Comment by boourns** [comment]
Awesome!

BTW - I'm getting some stickers printed, if you want, email your address to tom@burns.ca <mailto:tom@burns.ca> and I'll send you some!

**Pull request merged**
