### PR TITLE
Rename oliverb to miverb

### PR DESCRIPTION
**Pull request by NoraCodes**
Addresses #62

### CODE REVIEW

**Comment by NoraCodes** [comment]
Apologies for taking forever on this simple change. I got strep throat and then forgot about it :(

**Comment by boourns** [comment]
Looks great!  Thank you!

I may not end up merging this exact PR - I'm in the process of hiring a writer and we decided on this issue as a great first-commit for them to get their feet wet.  I'll leave it open and if they don't end up having time to do this I'll merge this copy.

**Comment by NoraCodes** [comment]
Oh, wondeful! I hope that pans out, and thank you for creating this excellent resource.

**Comment by boourns** [comment]
Merging this one, thanks again!

**Pull request merged**
