### PR TITLE
Add color reference for Erica Pico Logic

### PR DESCRIPTION
**Pull request by karlsander**
Since I never find that little card that came with the module...

I hope the XML stuff is right. I did an actual blinking animation for the blinking modes. If you think that's too harsh for the app than feel free to change it to the shimmer effect the other modules use for flashing.

### CODE REVIEW

**Comment by boourns** [comment]
awesome!  Great usecase for the app.  I will get this tested and merged before the next release.  Feel free to add "Cheat sheet by Karl Sander" to the info page if you would like.

**Comment by boourns** [comment]
Oops, I broke master by pushing half-completed warps documentation.. I did minor changes to the CSS (moved the erica stuff into it's own file until it's reused, added a class to the tables to make the LED column narrow).  Let me know in #12 how you would like to be credited for the contribution in the app.  

Thanks again!

**Comment by karlsander** [comment]
Looks good. I‘m good without credit in the app.

**Comment by boourns** [comment]
Ok!  If you change your mind let me know, cheers!

**Comment by boourns** [comment]
Hey @karlsander, I'm getting some Modes stickers printed.  Email your address to tom@burns.ca and I'll send you some!

Cheers

**Pull request merged**
